import { Icon } from "./icon";
import { Recipe } from "./recipe";

export interface Item {
    accuracy: number;
    armor_weight: number;
    atk_speed: number;
    baslik_loc_Chinese: string;
    baslik_loc_English: string;
    baslik_loc_French: string;
    baslik_loc_German: string;
    baslik_loc_Italian: string;
    baslik_loc_Japanese: string;
    baslik_loc_Korean: string;
    baslik_loc_Polish: string;
    baslik_loc_Portuguese: string;
    baslik_loc_Russian: string;
    baslik_loc_Spanish: string;
    baslik_loc_Turkish: string;
    baslik_loc_Ukrainian: string;
    casting_speed: number;
    default_grade: number;
    evasion: number;
    extra_damage_boss: number;
    extra_damage_mob: number;
    gender: number;
    hp: number;
    hp_regen: number;
    icon1: string;
    icon2: string;
    id: string;
    level: number;
    magic_ap: number;
    magic_dp: number;
    mp: number;
    mp_regen: number;
    physical_ap: number;
    physical_dp: number;
    purchase_price: number;
    repair_price: number;
    sale_price: number;
    satis_kapali: number;
    speed: number;
    tip_loc_Chinese: string;
    tip_loc_English: string;
    tip_loc_French: string;
    tip_loc_German: string;
    tip_loc_Italian: string;
    tip_loc_Japanese: string;
    tip_loc_Korean: string;
    tip_loc_Polish: string;
    tip_loc_Portuguese: string;
    tip_loc_Russian: string;
    tip_loc_Spanish: string;
    tip_loc_Turkish: string;
    tip_loc_Ukrainian: string;
    weight: number;
    icons: Icon;
    recipes: Recipe[];
    [key: string]: any;
}