import { Icon } from "./icon";
import { Recipe } from "./recipe";

export interface Prop {
    aciklama_ici_pr_1: string;
    aciklama_ici_pr_2: string;
    aciklama_ici_pr_3: string;
    aciklama_loc_Chinese: string;
    aciklama_loc_English: string;
    aciklama_loc_French: string;
    aciklama_loc_German: string;
    aciklama_loc_Italian: string;
    aciklama_loc_Japanese: string;
    aciklama_loc_Korean: string;
    aciklama_loc_Polish: string;
    aciklama_loc_Portuguese: string;
    aciklama_loc_Russian: string;
    aciklama_loc_Spanish: string;
    aciklama_loc_Turkish: string;
    aciklama_loc_Ukrainian: string;
    baslik_loc_Chinese: string;
    baslik_loc_English: string;
    baslik_loc_French: string;
    baslik_loc_German: string;
    baslik_loc_Italian: string;
    baslik_loc_Japanese: string;
    baslik_loc_Korean: string;
    baslik_loc_Polish: string;
    baslik_loc_Portuguese: string;
    baslik_loc_Russian: string;
    baslik_loc_Spanish: string;
    baslik_loc_Turkish: string;
    baslik_loc_Ukrainian: string;
    default_grade: number;
    icon1: string;
    id: string;
    level: number;
    max_saglik: number;
    purchase_price: number;
    sale_price: number;
    satis_kapali: number;
    tip_loc_Chinese: string;
    tip_loc_English: string;
    tip_loc_French: string;
    tip_loc_German: string;
    tip_loc_Italian: string;
    tip_loc_Japanese: string;
    tip_loc_Korean: string;
    tip_loc_Polish: string;
    tip_loc_Portuguese: string;
    tip_loc_Russian: string;
    tip_loc_Spanish: string;
    tip_loc_Turkish: string;
    tip_loc_Ukrainian: string;
    weight: number;
    icons: Icon;
    recipe: Recipe[];
    [key: string]: any;
}